### ISSUE TITLE
Artifacts deleted

### ISSUE THREAD

**Issue by jeeger** [MAXBURAOT/SmartSteamEmu#4]
Hey!
Unfortunately, the build artifacts have been deleted, which means the download link doesn't work. Re-running the build should fix this.

**Comment by Cerxi** [comment]
This happened again.

**Comment by Margen67** [comment]
This is due to AppVeyor's artifact retention policy: https://www.appveyor.com/blog/2018/05/24/artifacts-retention-policy/

**Comment by Margen67** [comment]
Here's a build I made with Visual Studio 2019 using AppVeyor: 
[SSELauncher.zip](https://github.com/MAXBURAOT/SmartSteamEmu/files/3963955/SSELauncher.zip)

If you don't trust it, you can build it yourself using this AppVeyor yml:
```
version: '{build}'

image: Visual Studio 2019

configuration: Release

build:
  project: SSELauncher.sln
  parallel: true

test: off

artifacts:
- path: bin\Release\SSELauncher.exe

deploy: off
```
